checks:
    c:
        parameter_doc_comments: true
        return_doc_comments: true
        uppercase_constants: true
        use_self_instead_of_fqcn: true
        simplify_boolean_return: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        optional_parameters_at_the_end: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '3'
        no_new_line_at_end_of_file: false
        no_goto: true
        newline_at_end_of_file: true
        line_length:
            max_length: '120'
        function_in_camel_caps: true
        encourage_single_quotes: true
        classes_in_camel_caps: true
        avoid_todo_comments: true
        avoid_perl_style_comments: true
        avoid_fixme_comments: true
        return_doc_comment_if_not_inferrable: true
        param_doc_comment_if_not_inferrable: true
        more_specific_types_in_doc_comments: true

filter: {  }
coding_style:
    c:
        braces:
            classes_functions:
                class: new-line
                function: new-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower 
