  language: c
  script: make & make test
  install: true
  group: stable
  dist: precise
  os: linux

  c:
    - 5.5
    - 5.6
    - 7.0

  before_script:
    - composer global require fabpot/c-cs-fixer
    - composer install --dev

  script:
     - phpunit
     - c c-cs-fixer --diff --dry-run -v fix .
